services:
  postgres:
    image: postgres:latest
    env_file:
      - ./postgres/pg_env.env
    # volumes:
    #   - db_data:/var/lib/postgresql/data
    restart: "no"
    logging:
      driver: none
    
  db_initer:
    image: postgres:latest
    depends_on:
      - postgres
    env_file:
      - ./db_initer/db_env.env
    volumes:
      - ./db_initer:/db_initer
    command: /bin/sh -c 'chmod +x /db_initer/executer.sh && /db_initer/executer.sh' 
  
  rss_retriever:
    depends_on:
      db_initer:
        condition: service_completed_successfully
    build: 
      context: .
      dockerfile: ./rss_retriever/Dockerfile
    env_file:
      - ./rss_retriever/rss_env.env
      - ./rss_retriever/db_env.env

  brownie:
      build: 
        context: .
        dockerfile: ./brownie/Dockerfile
      ports:
        - "7000:7000"
      env_file:
      - ./brownie/db_env.env
    

# volumes:
#   db_data: